name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # run every 5 minutes
  workflow_dispatch:         # allow manual runs too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping wearxture.com
        run: |
          echo "Pinging https://www.wearxture.com ..."
          for i in {1..3}; do
            if curl -s --head --fail https://www.wearxture.com > /dev/null; then
              echo "✅ Site is up (attempt $i)"
              exit 0
            else
              echo "⚠️ Attempt $i failed, retrying in 10s..."
              sleep 10
            fi
          done
          echo "❌ Site did not respond after 3 attempts"
          exit 1
