-- Drop the existing table and recreate with proper constraints
DROP TABLE IF EXISTS coupon_redemptions CASCADE;

-- Create coupon_redemptions table with proper unique constraint
CREATE TABLE coupon_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code TEXT NOT NULL,
    user_email TEXT NOT NULL,
    order_id TEXT NOT NULL,
    redemption_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    discount_amount INTEGER NOT NULL
);

-- Create unique constraint after table creation
ALTER TABLE coupon_redemptions
ADD CONSTRAINT unique_user_coupon UNIQUE (coupon_code, user_email);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_code_email ON coupon_redemptions(coupon_code, user_email);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_order ON coupon_redemptions(order_id);

-- Enable RLS
ALTER TABLE coupon_redemptions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow insert on coupon redemption" ON coupon_redemptions;
DROP POLICY IF EXISTS "Allow read access" ON coupon_redemptions;

-- Create policies
CREATE POLICY "Allow insert on coupon redemption" ON coupon_redemptions
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow read access" ON coupon_redemptions
    FOR SELECT USING (true);